/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 girls.gltf
Author: gragax (https://sketchfab.com/gragax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-girl-vr-sculpt-31994120724b4012a489aeae7ea0e564
Title: Stylized girl VR sculpt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/girls.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.06, 1.3, -0.01]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[0.01, 0, 0]} scale={2.47}>
      
            <mesh geometry={nodes.Layer_9__0_1.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_2.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_3.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_4.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_5.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_6.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_9__0_7.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0.11, 0.15]} scale={1.65}>
            <mesh geometry={nodes.Layer_4__0.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_4__0_1.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0, 0.03]} rotation={[-0.22, 0, 0]} scale={2.47}>
            <mesh geometry={nodes.Layer_15__0.geometry} material={materials['Scene_-_Root']} />
            <mesh geometry={nodes.Layer_15__0_1.geometry} material={materials['Scene_-_Root']} />
          </group>
          <mesh geometry={nodes.Layer_5__0.geometry} material={materials['Scene_-_Root']} position={[0, 0.03, 0.13]} scale={1.65} />
          <mesh geometry={nodes.Layer_6__0.geometry} material={materials['Scene_-_Root']} scale={3.7} />
          <mesh geometry={nodes.Layer_8__0.geometry} material={materials['Scene_-_Root']} scale={3.7} />
          <mesh geometry={nodes.Layer_11__0.geometry} material={materials['Scene_-_Root']} position={[-0.03, -0.04, -0.05]} rotation={[0.28, 0.61, -0.48]} scale={2.47} />
          <mesh geometry={nodes.Layer_22__0.geometry} material={materials['Scene_-_Root']} position={[0.3, 0.14, -0.22]} rotation={[2.7, 1.18, 0.81]} scale={2.44} />
          <mesh geometry={nodes.Layer_7__0.geometry} material={materials['Scene_-_Root']} scale={3.7} />
          <mesh geometry={nodes.Layer_11_1__0.geometry} material={materials['Scene_-_Root']} position={[0, -0.01, 0.03]} rotation={[-0.22, 0, 0]} scale={2.47} />
          <mesh geometry={nodes.Layer_22_1__0.geometry} material={materials['Scene_-_Root']} position={[0.16, 0.5, -0.3]} rotation={[-1.46, -0.01, 0.42]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1__0_1.geometry} material={materials['Scene_-_Root']} position={[0.18, 0.34, -0.11]} rotation={[-1.29, 1.34, -1.8]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0.geometry} material={materials['Scene_-_Root']} position={[0.18, 0.34, -0.11]} rotation={[-1.29, 1.34, -1.8]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0_1.geometry} material={materials['Scene_-_Root']} position={[0.27, 0.28, -0.2]} rotation={[-1.02, 0.48, 0.16]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_2__0.geometry} material={materials['Scene_-_Root']} position={[0.3, 0.18, -0.25]} rotation={[-2.72, 1.08, 0.33]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_3__0.geometry} material={materials['Scene_-_Root']} position={[0.18, 0.48, -0.3]} rotation={[-1.52, 0.03, 0.29]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_4__0.geometry} material={materials['Scene_-_Root']} position={[0.16, 0.4, -0.1]} rotation={[-0.32, 0.16, 1.04]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1_1__0.geometry} material={materials['Scene_-_Root']} position={[0.21, 0.32, -0.11]} rotation={[-0.47, 0.18, 0.51]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_3_1__0.geometry} material={materials['Scene_-_Root']} position={[0.06, 0.33, 0.03]} rotation={[0.06, -0.13, 1.08]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0_2.geometry} material={materials['Scene_-_Root']} position={[0.1, 0.34, 0]} rotation={[-0.09, -0.05, 0.99]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_4_1__0.geometry} material={materials['Scene_-_Root']} position={[0.22, 0.44, -0.32]} rotation={[-1.72, 0.25, 0.21]} scale={2.44} />
          <mesh geometry={nodes.Layer_22__0_1.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0_3.geometry} material={materials['Scene_-_Root']} position={[0.13, 0.36, -0.16]} rotation={[-1.79, 0.77, -0.93]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_2__0_1.geometry} material={materials['Scene_-_Root']} position={[0.13, 0.41, -0.03]} rotation={[-1.2, 0.61, -1.39]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_4_1__0_1.geometry} material={materials['Scene_-_Root']} position={[-0.19, 0.2, 0.27]} rotation={[0.15, -0.67, -1.82]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0_4.geometry} material={materials['Scene_-_Root']} position={[-0.16, 0.26, 0.25]} rotation={[-0.06, -0.79, -2.09]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1__0_2.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_4__0_1.geometry} material={materials['Scene_-_Root']} position={[-0.31, 0.04, 0.22]} rotation={[0.86, -0.89, -1.39]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_3__0_1.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1__0_3.geometry} material={materials['Scene_-_Root']} position={[-0.05, 0.33, 0.22]} rotation={[-0.31, -0.32, -1.98]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1__0_5.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_3_1__0_1.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_1_1__0_1.geometry} material={materials['Scene_-_Root']} position={[0.13, 0.36, -0.16]} rotation={[-1.79, 0.77, -0.93]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_2_1__0.geometry} material={materials['Scene_-_Root']} position={[0.03, 0.4, 0.12]} rotation={[-0.7, 0.14, -1.72]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_2_1_1__0.geometry} material={materials['Scene_-_Root']} position={[0, 0.36, 0.19]} rotation={[-0.47, -0.05, -1.85]} scale={2.44} />
          <mesh geometry={nodes.Layer_22_1_2_1_1_1__0.geometry} material={materials['Scene_-_Root']} position={[-0.08, 0.31, 0.23]} rotation={[-0.24, -0.31, -1.85]} scale={2.44} />
          <mesh geometry={nodes.Layer_11_1_1__0.geometry} material={materials['Scene_-_Root']} position={[-0.04, 0.04, 0.01]} rotation={[-0.5, -0.37, -0.06]} scale={2.47} />
          <mesh geometry={nodes.Layer_26__0.geometry} material={materials['Scene_-_Root']} position={[0.05, 0.97, -0.43]} rotation={[-0.97, -0.09, 0.26]} scale={5.31} />
          <mesh geometry={nodes.Layer_26_1__0.geometry} material={materials['Scene_-_Root']} position={[-0.3, 0.19, -0.15]} rotation={[-0.39, -0.26, -0.03]} scale={5.31} />
          <mesh geometry={nodes.Layer_26_1__0_1.geometry} material={materials['Scene_-_Root']} position={[0.34, -0.08, -0.12]} rotation={[-0.34, 0.4, -0.74]} scale={5.31} />
          <mesh geometry={nodes.Layer_26__0_1.geometry} material={materials['Scene_-_Root']} position={[0.62, 0.43, -0.39]} rotation={[-0.75, 0.62, -0.84]} scale={5.31} />
          <mesh geometry={nodes.Layer_13__0.geometry} material={materials['Scene_-_Root']} position={[-0.01, -0.05, 0.01]} rotation={[-0.04, 0.07, -0.04]} scale={3.71} />
          <mesh geometry={nodes.Layer_13__0_1.geometry} material={materials['Scene_-_Root']} position={[-0.04, -0.04, 0.01]} rotation={[-0.24, -0.33, 0.26]} scale={3.71} />
          <mesh geometry={nodes.Layer_11_1_2__0.geometry} material={materials['Scene_-_Root']} position={[0, -0.01, 0.03]} rotation={[-0.22, 0, 0]} scale={2.47} />
          <mesh geometry={nodes.Layer_19__0.geometry} material={materials['Scene_-_Root']} position={[0.2, -0.16, -0.01]} rotation={[0.18, 0.54, -0.27]} scale={5.27} />
          <mesh geometry={nodes.Layer_19__0_1.geometry} material={materials['Scene_-_Root']} position={[-0.32, 0.1, -0.05]} rotation={[-0.45, -0.65, -0.28]} scale={5.27} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/girls.gltf')
