/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 knight.gltf
Author: Muru (https://sketchfab.com/muru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/knight-cat-adb1d82f85f74ef6b2947b517b6987f6
Title: Knight Cat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/knight.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface23_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube3_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface30_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface31_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface11_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface12_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface10_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube4_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube5_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube6_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder2_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder3_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCylinder4_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface13_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface18_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface19_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface22_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface21_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface20_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface14_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pPlane1_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pPlane2_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface27_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface32_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/knight.gltf')
